# Generated by Django 4.1.1 on 2022-12-03 10:25

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50, verbose_name='Район')),
            ],
        ),
        migrations.CreateModel(
            name='Loiha41',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_sum_industry', models.FloatField(blank=True)),
                ('picture_of_growth_industry', models.FloatField(blank=True)),
                ('forecast_industry', models.FloatField(blank=True)),
                ('difference_industry', models.FloatField(blank=True)),
                ('bill_sum_locality', models.FloatField(blank=True)),
                ('picture_of_growth_locality', models.FloatField(blank=True)),
                ('forecast_locality', models.FloatField(blank=True)),
                ('difference_locality', models.FloatField(blank=True)),
                ('bill_sum_construction', models.FloatField(blank=True)),
                ('picture_of_growth_construction', models.FloatField(blank=True)),
                ('forecast_construction', models.FloatField(blank=True)),
                ('difference_construction', models.FloatField(blank=True)),
                ('bill_sum_services', models.FloatField(blank=True)),
                ('picture_of_growth_services', models.FloatField(blank=True)),
                ('forecast_services', models.FloatField(blank=True)),
                ('difference_services', models.FloatField(blank=True)),
                ('bill_sum_retail', models.FloatField(blank=True)),
                ('picture_of_growth_retail', models.FloatField(blank=True)),
                ('forecast_retail', models.FloatField(blank=True)),
                ('difference_retail', models.FloatField(blank=True)),
                ('thousand_dollar_international_trade', models.FloatField(blank=True)),
                ('picture_of_growth_international_trade', models.FloatField(blank=True)),
                ('thousand_dollar_export', models.FloatField(blank=True)),
                ('picture_of_growth_export', models.FloatField(blank=True)),
                ('thousand_dollar_import', models.FloatField(blank=True)),
                ('picture_of_growth_import', models.FloatField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
