# Generated by Django 4.1.5 on 2023-01-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_loiha10_beekeeping_specialty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loiha41',
            options={'ordering': ['-time_update'], 'verbose_name': 'Таблица 4.1', 'verbose_name_plural': 'Таблицы 4.1'},
        ),
    ]
