# Generated by Django 4.1.5 on 2023-01-25 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_loiha41_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loiha41',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 9, 59, 53, 679570, tzinfo=datetime.timezone.utc), verbose_name='Дата и время создания'),
        ),
    ]
