# Generated by Django 4.1.5 on 2023-02-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_bankvault_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejavault',
            name='istik_ish',
            field=models.CharField(default='', max_length=255, verbose_name='Иш ўрни'),
        ),
        migrations.AddField(
            model_name='rejavault',
            name='istik_kredit',
            field=models.CharField(default='', max_length=255, verbose_name='анк кредитлари млн.сўм'),
        ),
        migrations.AddField(
            model_name='rejavault',
            name='istik_loiha_kiymati',
            field=models.CharField(default='', max_length=255, verbose_name='Лойиҳа қиймати, (млн.сўм)'),
        ),
        migrations.AddField(
            model_name='rejavault',
            name='istik_loiha_soni',
            field=models.CharField(default='', max_length=255, verbose_name='Лойиҳа сони'),
        ),
        migrations.AddField(
            model_name='rejavault',
            name='istik_mablag',
            field=models.CharField(default='', max_length=255, verbose_name='ўз маблағлари млн.сўм'),
        ),
        migrations.AddField(
            model_name='rejavault',
            name='istik_xorijiy_invest',
            field=models.CharField(default='', max_length=255, verbose_name='хорижий инвестициялар минг.долл '),
        ),
        migrations.AddField(
            model_name='rejavault',
            name='istik_xorijiy_kredit',
            field=models.CharField(default='', max_length=255, verbose_name='хорижий кредитлар минг.долл'),
        ),
    ]
