# Generated by Django 4.1.1 on 2022-12-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_district_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.district'),
        ),
    ]
