# Generated by Django 4.1.1 on 2022-12-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_customuser_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.district'),
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Район'),
        ),
    ]
