# Generated by Django 4.1.1 on 2022-12-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_customuser_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loiha10',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 10', 'verbose_name_plural': 'Таблицы 10'},
        ),
        migrations.AlterModelOptions(
            name='loiha12',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 12', 'verbose_name_plural': 'Таблицы 12'},
        ),
        migrations.AlterModelOptions(
            name='loiha121',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 12.1', 'verbose_name_plural': 'Таблицы 12.1'},
        ),
        migrations.AlterModelOptions(
            name='loiha122',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 12.2', 'verbose_name_plural': 'Таблицы 12.2'},
        ),
        migrations.AlterModelOptions(
            name='loiha13',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 13', 'verbose_name_plural': 'Таблицы 13'},
        ),
        migrations.AlterModelOptions(
            name='loiha131',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 13.1', 'verbose_name_plural': 'Таблицы 13.1'},
        ),
        migrations.AlterModelOptions(
            name='loiha14',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 14', 'verbose_name_plural': 'Таблицы 14'},
        ),
        migrations.AlterModelOptions(
            name='loiha52',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 5.2', 'verbose_name_plural': 'Таблицы 5.2'},
        ),
        migrations.AlterModelOptions(
            name='loiha6',
            options={'ordering': ['time_create'], 'verbose_name': 'Таблица 6', 'verbose_name_plural': 'Таблицы 6'},
        ),
    ]
