# Generated by Django 4.1.1 on 2023-01-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_loiha10_options_alter_loiha12_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loiha10',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 10', 'verbose_name_plural': 'Таблицы 10'},
        ),
        migrations.AlterModelOptions(
            name='loiha12',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 12', 'verbose_name_plural': 'Таблицы 12'},
        ),
        migrations.AlterModelOptions(
            name='loiha121',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 12.1', 'verbose_name_plural': 'Таблицы 12.1'},
        ),
        migrations.AlterModelOptions(
            name='loiha122',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 12.2', 'verbose_name_plural': 'Таблицы 12.2'},
        ),
        migrations.AlterModelOptions(
            name='loiha13',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 13', 'verbose_name_plural': 'Таблицы 13'},
        ),
        migrations.AlterModelOptions(
            name='loiha131',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 13.1', 'verbose_name_plural': 'Таблицы 13.1'},
        ),
        migrations.AlterModelOptions(
            name='loiha14',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 14', 'verbose_name_plural': 'Таблицы 14'},
        ),
        migrations.AlterModelOptions(
            name='loiha41',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 4.1', 'verbose_name_plural': 'Таблицы 4.1'},
        ),
        migrations.AlterModelOptions(
            name='loiha52',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 5.2', 'verbose_name_plural': 'Таблицы 5.2'},
        ),
        migrations.AlterModelOptions(
            name='loiha6',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таблица 6', 'verbose_name_plural': 'Таблицы 6'},
        ),
        migrations.AddField(
            model_name='loiha52',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
