# Generated by Django 4.1.5 on 2023-01-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_loiha10_options_alter_loiha12_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loiha10',
            name='Beekeeping_specialty',
            field=models.CharField(max_length=255, verbose_name='пчеловодство'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='animal_husbandry_speciality',
            field=models.CharField(max_length=255, verbose_name='животноводство'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='employed_in_the_sector',
            field=models.CharField(max_length=255, verbose_name='дома занятые в секторе'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='farm_specialty',
            field=models.CharField(max_length=255, verbose_name='фермерство'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='gardening_specialty',
            field=models.CharField(max_length=255, verbose_name='садоводство'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='greenhouses_specialty',
            field=models.CharField(max_length=255, verbose_name='парники'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='locality_amount',
            field=models.CharField(max_length=255, verbose_name='насленный пункт (количество)'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='other_specialty',
            field=models.CharField(max_length=255, verbose_name='другие'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='percent_residential_buildings',
            field=models.CharField(max_length=255, verbose_name='процентное соотношение'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='poultry_farming_specialty',
            field=models.CharField(max_length=255, verbose_name='птицеводство'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='rabbing_breeding_specialty',
            field=models.CharField(max_length=255, verbose_name='кроликоведение'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='remaining_on_the_iron_notebook',
            field=models.CharField(max_length=255, verbose_name='железная тетрадь оставшиеся'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='remaining_on_the_womens_notebook',
            field=models.CharField(max_length=255, verbose_name='женская тетрадь оставшиеся'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='remaining_on_the_youth_notebook',
            field=models.CharField(max_length=255, verbose_name='молодёжная тетрадь оставшиеся'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='residential_buildings_amount',
            field=models.CharField(max_length=255, verbose_name='Жилые дома (количество)'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='services_specialty',
            field=models.CharField(max_length=255, verbose_name='услуги'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='small_production_specialty',
            field=models.CharField(max_length=255, verbose_name='мелькое производство'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='teaching_specialty',
            field=models.CharField(max_length=255, verbose_name='преподование'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='tourism_specialty',
            field=models.CharField(max_length=255, verbose_name='туризм'),
        ),
        migrations.AlterField(
            model_name='loiha10',
            name='who_want_to_do_business_residential_buildings',
            field=models.CharField(max_length=255, verbose_name='Желающие заняться предпринимательством (количество)'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='all_projects',
            field=models.CharField(max_length=255, verbose_name='Все проекты'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='all_projects_at_work_from_all_projects',
            field=models.CharField(max_length=255, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='all_projects_will_be_completed_end_the_year_from_all_projects',
            field=models.CharField(max_length=255, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='grade',
            field=models.CharField(max_length=255, verbose_name='Оценка(млрд долл)'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='grade_at_work_from_all_projects',
            field=models.CharField(max_length=255, verbose_name='Оценка (млрд долл)'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='grade_selected_projects_from_all_projects',
            field=models.CharField(max_length=255, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='grade_will_be_completed_end_the_year_all_projects',
            field=models.CharField(max_length=255, verbose_name='Оценка (млрд долл)'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='projects_selected_projects_from_all_projects',
            field=models.CharField(max_length=255, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='workplace',
            field=models.CharField(max_length=255, verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='workplace_at_work_from_all_projects',
            field=models.CharField(max_length=255, verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='workplace_selected_projects_from_all_projects',
            field=models.CharField(max_length=255, verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='loiha12',
            name='workplace_will_be_completed_end_the_year_all_projects',
            field=models.CharField(max_length=255, verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='approved_holding_companies',
            field=models.CharField(max_length=255, verbose_name='Утвержденные холдинговые компании количество'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='entrepreneur',
            field=models.CharField(max_length=255, verbose_name='Предложения предпринимателей(ф.и.о)'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='export_stated_results',
            field=models.CharField(max_length=255, verbose_name='Экспорт'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='financing',
            field=models.CharField(max_length=255, verbose_name='Финансирование'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='grade_stated_results',
            field=models.CharField(max_length=255, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='names_of_organizations_priority',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='other_stated_results',
            field=models.CharField(max_length=255, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='productive_capacity_stated_results',
            field=models.CharField(max_length=255, verbose_name='Производственная мощность'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='projects_the_stated_results',
            field=models.CharField(max_length=255, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='type_of_activity_priority',
            field=models.CharField(max_length=255, verbose_name='Тип деятельности'),
        ),
        migrations.AlterField(
            model_name='loiha121',
            name='workplace_stated_results',
            field=models.CharField(max_length=255, verbose_name='Рабочее место'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='bank_loan_grade_at_work',
            field=models.CharField(max_length=255, verbose_name='Банковский кредит'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='export_volume_at_work',
            field=models.CharField(max_length=255, verbose_name='Обьем экспорта'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='foreign_investments_grade_at_work',
            field=models.CharField(max_length=255, verbose_name='Иностранные инвестиции'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='formed_tips',
            field=models.CharField(max_length=255, verbose_name='Сформированные советы'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='grade_at_work',
            field=models.CharField(max_length=255, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='name_bank_financing',
            field=models.CharField(max_length=255, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='name_country_financing',
            field=models.CharField(max_length=255, verbose_name='название страны'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='organization_name_foreign_financing',
            field=models.CharField(max_length=255, verbose_name='название организации'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='own_funds_grade_at_work',
            field=models.CharField(max_length=255, verbose_name='Собственные средства'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='production_capacity_at_work',
            field=models.CharField(max_length=255, verbose_name='Производсвенные мощности'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='projects_at_work',
            field=models.CharField(max_length=255, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha122',
            name='workplace_at_work',
            field=models.CharField(max_length=255, verbose_name='Уровнь работы'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='created_new_jobs',
            field=models.CharField(max_length=255, verbose_name='Cозданные новые рабочие места'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='foreign_financing_grate_sources_of_financing',
            field=models.CharField(max_length=255, verbose_name='Иностранные инвестиции'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='grate_sources_of_financing',
            field=models.CharField(max_length=255, verbose_name='Оценка в миллиардах долларах'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='project_activity',
            field=models.CharField(max_length=255, verbose_name='Проектная деятельность'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='project_capacity',
            field=models.CharField(max_length=255, verbose_name='Проектная мощность'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='sources_sources_of_financing',
            field=models.CharField(max_length=255, verbose_name='Источники'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha13',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='bank_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='bureaucratic_obstacles_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Бюрокартический барьер'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='customs_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Таможня'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='identified_problems',
            field=models.CharField(max_length=255, verbose_name='Известные проблемы'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='land_and_building_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Земля и здание'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='other_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Другое'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='permission_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Разрешения'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='public_services_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Коммунальные'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='resolved_problems_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Решенные проблемы'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='tax_identified_problems',
            field=models.CharField(max_length=255, verbose_name='Налог'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha131',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='available_jobs_available_information',
            field=models.CharField(max_length=255, verbose_name='Имеющиеся рабочие места'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='bank_loan_grade_at_work',
            field=models.CharField(max_length=255, verbose_name='Банковский кредит'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='created_new_jobs_at_work',
            field=models.CharField(max_length=255, verbose_name='Созданные рабочие места'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='export_volume_at_work',
            field=models.CharField(max_length=255, verbose_name='Обьем экспорта (млрд долл)'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='grade_at_work',
            field=models.CharField(max_length=255, verbose_name='Оценка (млрд долл)'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='kind_of_activity_available_information',
            field=models.CharField(max_length=255, verbose_name='Род деятельности'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='name_bank_financing',
            field=models.CharField(max_length=255, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='name_country_financing',
            field=models.CharField(max_length=255, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='organization_available_information',
            field=models.CharField(max_length=255, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='organization_name_foreign_financing',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='own_funds_grade_at_work',
            field=models.CharField(max_length=255, verbose_name='Собственные средства'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='project_activity_at_work',
            field=models.CharField(max_length=255, verbose_name='Проектная деятельность'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='sources_sources_of_financing',
            field=models.CharField(max_length=255, verbose_name='Иностранные инвестиции'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha14',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='bill_sum_construction',
            field=models.FloatField(blank=True, verbose_name="mlrd. so'm"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='bill_sum_industry',
            field=models.FloatField(blank=True, verbose_name="mlrd. so'm"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='bill_sum_locality',
            field=models.FloatField(blank=True, verbose_name="mlrd. so'm"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='bill_sum_retail',
            field=models.FloatField(blank=True, verbose_name="mlrd. so'm"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='bill_sum_services',
            field=models.FloatField(blank=True, verbose_name="mlrd. so'm"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='difference_construction',
            field=models.FloatField(blank=True, verbose_name='farqi (-;+)'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='difference_industry',
            field=models.FloatField(blank=True, verbose_name='farqi (-;+)'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='difference_locality',
            field=models.FloatField(blank=True, verbose_name='farqi (-;+)'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='difference_retail',
            field=models.FloatField(blank=True, verbose_name='farqi (-;+)'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='difference_services',
            field=models.FloatField(blank=True, verbose_name='farqi (-;+)'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='forecast_construction',
            field=models.FloatField(blank=True, verbose_name='prognoz'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='forecast_industry',
            field=models.FloatField(blank=True, verbose_name='prognoz'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='forecast_locality',
            field=models.FloatField(blank=True, verbose_name='prognoz'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='forecast_retail',
            field=models.FloatField(blank=True, verbose_name='prognoz'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='forecast_services',
            field=models.FloatField(blank=True, verbose_name='prognoz'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='picture_of_growth_construction',
            field=models.FloatField(blank=True, verbose_name="o'shish sur'ti%"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='picture_of_growth_export',
            field=models.FloatField(blank=True, verbose_name="o'shish sur'ti%"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='picture_of_growth_import',
            field=models.FloatField(blank=True, verbose_name="o'shish sur'ti%"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='picture_of_growth_industry',
            field=models.FloatField(blank=True, verbose_name="o'shish sur'ti%"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='picture_of_growth_international_trade',
            field=models.FloatField(blank=True, verbose_name="o'shish sur'ti%"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='picture_of_growth_locality',
            field=models.FloatField(blank=True, verbose_name="o'shish sur'ti%"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='picture_of_growth_retail',
            field=models.FloatField(blank=True, verbose_name="o'shish sur'ti%"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='picture_of_growth_services',
            field=models.FloatField(blank=True, verbose_name="o'shish sur'ti%"),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='thousand_dollar_export',
            field=models.FloatField(blank=True, verbose_name='ming. AQSh doll'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='thousand_dollar_import',
            field=models.FloatField(blank=True, verbose_name='ming. AQSh doll'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='thousand_dollar_international_trade',
            field=models.FloatField(blank=True, verbose_name='ming. AQSh doll'),
        ),
        migrations.AlterField(
            model_name='loiha41',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='abc_categories',
            field=models.FloatField(blank=True, verbose_name='A+B+C1 категории'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='c2_category',
            field=models.FloatField(blank=True, verbose_name='С2 категория'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='confirmed_stock_and_date',
            field=models.CharField(max_length=255, verbose_name='Подтвержденный отчет о запасах и его дата'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='date_license_operational_information',
            field=models.CharField(max_length=255, verbose_name='Дата и номер лицензии'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='lvl_development_operational_information',
            field=models.CharField(max_length=255, verbose_name='Уровень развития'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='ministry_and_department',
            field=models.CharField(max_length=255, verbose_name='Соответствующее министерство и ведомство'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='name_of_formations',
            field=models.CharField(max_length=255, verbose_name='Наименование месторождений геологических формаций (сырых)'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='places_of_exploration',
            field=models.CharField(max_length=255, verbose_name='Название места, где расположены природные ресурсы(Объекты геологоразведки)'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='sites_of_geo_formations',
            field=models.CharField(max_length=255, verbose_name='Участки геологических образований'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='unit',
            field=models.CharField(max_length=255, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='loiha52',
            name='volume_of_production_2017',
            field=models.FloatField(blank=True, verbose_name='Объем добычи в 2017 г.'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='Investment_proposals_sources',
            field=models.CharField(max_length=255, verbose_name='Предложения по инвестициям (источники)'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='adress_empty_objects',
            field=models.CharField(max_length=255, verbose_name='Aдрес'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='empty_objects',
            field=models.CharField(max_length=255, verbose_name='Пустующие объекты'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='focused_on_agriculture_unused_production_sites',
            field=models.FloatField(blank=True, verbose_name='ориентированное на сельское хозяйство(Га)'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='focused_on_production_unused_production_sites',
            field=models.FloatField(blank=True, verbose_name='ориентированное на производство(Га)'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='new_jobs_created_amount_sources',
            field=models.CharField(max_length=255, verbose_name='количество созданных навых рабочих мест'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='owner_empty_objects',
            field=models.CharField(max_length=255, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='preliminary_project_cost_bil_sum_sources',
            field=models.CharField(max_length=255, verbose_name='Предварительная стоимость проекта(млн.долл)'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='private_property_amount_empty_objects',
            field=models.CharField(max_length=255, verbose_name='частное имущуство (количество)'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='state_property_amount_empty_objects',
            field=models.CharField(max_length=255, verbose_name='государственное имущество (количество)'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи'),
        ),
        migrations.AlterField(
            model_name='loiha6',
            name='unused_production_sites',
            field=models.FloatField(blank=True, verbose_name='Неиспользуемые производственные площадки(Га)'),
        ),
    ]
