# Generated by Django 4.1.5 on 2023-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_sanoat_kunliu_kh_firsttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunliu',
            name='overall',
            field=models.CharField(default='', max_length=255, verbose_name='всего'),
        ),
    ]
