# Generated by Django 4.1.5 on 2023-02-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_monthvault_september_budget_amalda'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankvault',
            name='bank_name',
            field=models.CharField(default='', max_length=255, verbose_name='Banklar nomi'),
        ),
    ]
