# Generated by Django 4.1.5 on 2023-02-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rejavault_istik_ish_rejavault_istik_kredit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarmokvault',
            name='tormok_name',
        ),
        migrations.AddField(
            model_name='tarmokvault',
            name='category',
            field=models.CharField(choices=[('SANOAT_YO`NALISHI', 'Саноат йўналиши'), ('HIZMAT_KO`RSATISH_SOHASI', 'Хизмат кўрсатиш соҳаси'), ('KISHLOQ_HO`ZALIGI_YO`NALISHI', 'Қишлоқ хўжалиги йўналиши')], default='SANOAT_YO`NALISHI', max_length=255, verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='tarmokvault',
            name='industry',
            field=models.CharField(choices=[('pharmaceuticals', 'Фармацевтика саноати'), ('textile_clothing', 'Текстиль ва тўқимачилик саноати'), ('furniture_wood', 'Мебель ва қоғоз саноати'), ('agriculture_livestock', 'Озиқ-овқат саноати'), ('building_materials', 'Қурилиш материаллари саноати'), ('chemical_paints', 'Чарм-пойабзал саноати'), ('metallurgical', 'Металлургия саноати'), ('chemicals', 'Кимё саноати'), ('machine_building', 'Машинасозлик ва эҳтиёт қисмлар саноати'), ('ipakchilik_sanoat', 'Ипакчилик саноати'), ('ozuqa_em_mahsolatlar_islab_chikarish_sanoat', 'Озуқа ем маҳсулотлари ишлаб чиқариш саноати'), ('yoqilgi-energetika_sanoat', 'Ёқилғи-энергетика саноати'), ('yog-moi_sanoat', 'Ёғ-мой саноати'), ('elektrotexnika_sanoat', 'Электротехника саноати'), ('neftgaz_sanoat', 'Нефтегаз саноати'), ('tog-kon_sanoat', 'Тоғ-кон саноати'), ('zargarlik_sanoat', 'Заргарлик саноати'), ('bashqa_sanoat_tarmoklari', 'Бошқа саноат тармоқлари'), ('auto', 'Автомобилларга техник хизмат кўрсатиш хизматлари'), ('security', 'Алоқа ва ахборотлаштириш хизмати'), ('restaurant', 'Замонавий уй-жойлар қуриш'), ('cafe', 'Кафе ва ресторан хизматлари'), ('fashion', 'Қушхона хизматлари'), ('hairdressing', 'Маиший хизмат кўрсатиш'), ('wedding', 'Меҳмонхона хизмати'), ('makeup', 'Савдо хизматлари'), ('cleaning', 'Соғлиқни сақлаш соҳасидаги хизматлар'), ('sports', 'Спорт ва соғломлаштириш хизматлари'), ('education', 'Таълим хизматлари'), ('transportation', 'Транспорт хизматлари'), ('tourism', 'Туризм хизматлари'), ('repair', 'Қурилиш соҳасидаги хизматлар'), ('construction', 'Қишлоқ хўжалиги хизматлари'), ('other', 'Бошқа турдаги хизматлар'), ('agro_cluster', 'Агро кластер ташкил этиш'), ('asalari_revitalization', 'Асаларичиликни ривожлантириш'), ('balik_revitalization', 'Балиқчиликни ривожлантириш'), ('bogodar_revitalization', 'Боғдорчиликни ривожлантириш'), ('dorivor_etishtirish', 'Доривор ўсимликлар етиштириш'), ('zamona_issikho_etish', 'Замонавий иссиқхона ташкил этиш'), ('intensive_industry', 'Интенсив боғ ташкил қилиш'), ('kislok_industry_etishtirish', 'Қишлоқ хўжалиги маҳсулотларини етиштириш'), ('quyodar_revitalization', 'Қуёнчиликни ривожлантириш'), ('logistics_marks', 'Логистика марказлари'), ('muslatkich_omborho_etish', 'Музлаткичли омборхона ташкил этиш'), ('parranda_revitalization', 'Паррандачиликни ривожлантириш'), ('pahta_etish', 'Пахта-тўқимачилик кластерини ташкил этиш'), ('gallachilik_cluster', 'Галлачилик кластери'), ('pilla_revitalization', 'Пиллачиликни ривожлантириш'), ('UZMCH_RI', 'Узумчиликни ривожлантириш'), ('CRVCH_RI', 'Чорвачиликни ривожлантириш'), ('TMCHL_SG', 'Томчилатиб суғориш'), ('BSHQ_QLHZ_TR', 'Бошқа қишлоқ хўжалиги тармоқлари')], default='pharmaceuticals', max_length=255, verbose_name='Тармоқлар номи'),
        ),
    ]
